---
name: Linux Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Python support libs
        run: |
          pip install --upgrade pip pipenv-to-requirements pep517
          pipenv_to_requirements
          pip install -r requirements-dev.txt
      - name: Build and run tests
        run: |
          pytest --cov=curitiba_dados_abertos --cov-fail-under=68 -s
          pep517.build --source --binary --out-dir dist/
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
